<?xml version="1.0" encoding="UTF-8"?>
<project name="HTTH129J2ME" default="default" basedir=".">
    <description>Builds, tests, and runs the project HTTH129J2ME.</description>

    <import file="nbproject/build-impl.xml"/>

    <target name="-post-jar">
        <!-- Ghi đè manifest -->
        <jar destfile="${dist.jar}" manifest="${manifest.file}" update="false">
            <fileset dir="${build.classes.dir}"/>
        </jar>
    </target>

    <target name="run-jar" description="Run HaiTacTiHon129.jad in AngelChip Emulator">
        <java jar="AngelChipEmulator_AutoSleep.jar" fork="true">
            <arg value="HaiTacTiHon129.jad"/>
        </java>
    </target>

    <target name="build-jar" description="Build and obfuscate deliverable JAR using build_ultimate.bat">
        <exec executable="cmd.exe" dir="${basedir}">
            <arg line="/c build_ultimate.bat"/>
        </exec>
    </target>
</project>

