port=2239
mysql-host=localhost
mysql-user=root
mysql-password=
mysql-database=haitacz
debug=false
exp=1
serveradmin=false
cache-max-ram-entries=-1
cache-enable-ssd=true
auto-restart=true
auto-baotri-midnight=true
trade-min-online-hours=48
check_client_key=true
client_secret_key=HTTH_CLIENT_NAMTR0002_SECURE_KEY_V4_2026